# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shebei.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QTableView, QHeaderView, QTableWidget, QTableWidgetItem
import chanjia2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets


class chajia1_Form(object):
    def setupUi1(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 140, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(330, 160, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        # self.comboBox.addItem("")

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(340, 250, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 250, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(self.call_chanjia)
        self.pushButton.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "请选择要查询的设备名称："))
        self.comboBox.setItemText(0, _translate("Form", "全部厂家"))
        self.comboBox.setItemText(1, _translate("Form", "35kV SF6气体在线检测装置"))
        self.comboBox.setItemText(2, _translate("Form", "调度数据网，二次安防"))
        self.comboBox.setItemText(3, _translate("Form", "故障录波"))
        self.comboBox.setItemText(4, _translate("Form", "国电南瑞"))
        self.comboBox.setItemText(5, _translate("Form", "五防厂家"))
        self.comboBox.setItemText(6, _translate("Form", "功率预测厂家"))
        self.comboBox.setItemText(7, _translate("Form", "高压开关柜厂家"))
        self.comboBox.setItemText(8, _translate("Form", "充氮灭火器厂家"))
        self.comboBox.setItemText(9, _translate("Form", "电能量采集终端（华立）"))
        self.comboBox.setItemText(10, _translate("Form", "电能量采集终端（威思顿）"))
        self.comboBox.setItemText(11, _translate("Form", "恶意代码"))
        self.comboBox.setItemText(12, _translate("Form", "小电阻接地变成套装置"))
        self.comboBox.setItemText(13, _translate("Form", "GIS（西电）"))
        self.comboBox.setItemText(14, _translate("Form", "主变（华鹏）"))
        self.comboBox.setItemText(15, _translate("Form", "35kV，400V开关柜（泰开）"))
        self.comboBox.setItemText(16, _translate("Form", "SVG（新风光）"))
        self.comboBox.setItemText(17, _translate("Form", "数据网，网络安全监测"))
        self.comboBox.setItemText(18, _translate("Form", "光端机通信（西安德悦）"))
        self.comboBox.setItemText(19, _translate("Form", "交直流（许继电源）"))
        self.comboBox.setItemText(20, _translate("Form", "交直流（许继电源）"))
        self.comboBox.setItemText(21, _translate("Form", "主变温控箱（福建力得）"))
        self.comboBox.setItemText(22, _translate("Form", "站用变（泰开箱变）"))
        self.pushButton.setText(_translate("Form", "取消"))
        self.pushButton_2.setText(_translate("Form", "确定"))

    def call_chanjia(self):
        combo_text = self.comboBox.currentText()
        # print(combo_text)
        self.main_window=chanjia2.chanjia2()
        self.main_window.keshihua2(combo_text)
        self.main_window.show()


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    my_form = QtWidgets.QWidget()
    ui = chajia1_Form()
    ui.setupUi1(my_form)
    my_form.show()
    sys.exit(app.exec_())