# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import QApplication, QTableView, QHeaderView, QTableWidget, QTableWidgetItem
# import keshihua
from PyQt5 import QtCore, QtGui, QtWidgets
import shebei1

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("信息查询")
        Form.resize(640, 480)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 130, 141, 31))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(270, 130, 131, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(160, 230, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 230, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(self.call_keshihua)
        self.pushButton_2.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "信息查询"))
        self.label.setText(_translate("Form", "请输入要查询的信息："))
        self.comboBox.setItemText(0, _translate("Form", "设备基础信息统计表"))
        self.comboBox.setItemText(1, _translate("Form", "厂家联系方式"))
        self.comboBox.setItemText(2, _translate("Form", "场站人员名单"))
        self.comboBox.setItemText(3, _translate("Form", "场站休假人员名单"))
        self.pushButton.setText(_translate("Form", "确定"))
        self.pushButton_2.setText(_translate("Form", "取消"))

    def call_keshihua(self):
        # text = self.lineEdit.text()
        combo_text = self.comboBox.currentText()
        # print(text)
        # my_form.close()

        if combo_text =='设备基础信息统计表':
            self.main_window = shebei.shebei_Form()
            self.main_window.call_shebei()
            self.main_window.show()




"""
# 假设已经创建了一个名为label和comboBox的QLabel和QComboBox对象

# 获取QLabel的文本
label_text = label.text()
print("Label文本:", label_text)

# 获取QComboBox的当前选中文本
combo_text = comboBox.currentText()
print("ComboBox当前选中文本:", combo_text)
"""

if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    my_form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(my_form)
    my_form.show()
    sys.exit(app.exec_())