# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shebei.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QTableView, QHeaderView, QTableWidget, QTableWidgetItem
import shebei2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets


class shebei_Form(object):
    def setupUi1(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 140, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(330, 160, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(340, 250, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 250, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        self.pushButton_2.clicked.connect(self.call_shebei)
        self.pushButton.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "请选择要查询的设备名称："))
        self.comboBox.setItemText(0, _translate("Form", "送出线路"))
        self.comboBox.setItemText(1, _translate("Form", "GIS"))
        self.comboBox.setItemText(2, _translate("Form", "主变"))
        self.comboBox.setItemText(3, _translate("Form", "高压设备开关"))
        self.comboBox.setItemText(4, _translate("Form", "400V配电系统"))
        self.comboBox.setItemText(5, _translate("Form", "集电线路"))
        self.comboBox.setItemText(6, _translate("Form", "箱变"))
        self.comboBox.setItemText(7, _translate("Form", "逆变器"))
        self.comboBox.setItemText(8, _translate("Form", "综合自动化装置及继电保护装置"))
        self.comboBox.setItemText(9, _translate("Form", "直流系统"))
        self.comboBox.setItemText(10, _translate("Form", "UPS系统"))
        self.comboBox.setItemText(11, _translate("Form", "通讯系统"))
        self.comboBox.setItemText(12, _translate("Form", "全部信息"))
        self.pushButton.setText(_translate("Form", "取消"))
        self.pushButton_2.setText(_translate("Form", "确定"))

    def call_shebei(self):
        combo_text = self.comboBox.currentText()
        # print(combo_text)
        self.main_window=shebei2.shebei()
        self.main_window.keshihua2(combo_text)
        self.main_window.show()


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    my_form = QtWidgets.QWidget()
    ui = shebei_Form()
    ui.setupUi1(my_form)
    my_form.show()
    sys.exit(app.exec_())